# Copyright (C) 2019-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (C) 2019-present Sven Greb <development@svengreb.de>
#
# Project:    Arctic Ocean Fractal
# Repository: https://github.com/arcticicestudio/arctic-ocean-fractal
# License:    MIT

# Configuration for SVGO.
#
# References:
# - https://github.com/svg/svgo
# - https://github.com/svg/svgo/blob/master/.svgo.yml

multipass: true
js2svg:
  pretty: true
  indent: 2
